apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes-deployment
  labels:
    app: springboot-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-kubernetes
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
      - name: springboot-kubernetes
        image: shouvick/spring-boot-sample
        ports:
          - containerPort: 80